// src/app/card/card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { animate, state, style, transition, trigger } from '@angular/animations'
import debounce from 'lodash/debounce';
import moment from 'moment';
import { Card } from './card.model';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.scss'],
  animations: [
    trigger('iconFlipState', [
      state('normal', style({
        transform: 'rotateY(0deg)'
      })),
      state('highlighted', style({
        transform: 'rotateY(180deg)'
      })),
      state('end', style({
        transform: 'rotateY(360deg)'
      })),
      transition('normal => end', animate(500))
    ])
  ]
})

export class CardComponent {
  iconFlipState = 'normal';
  prefetchedLocations: string[] = [];
  @Input() card: Card | any;
  @Input() first: boolean = false;

  goto(gotoLocation: string) {
      document.location.pathname = gotoLocation
  }

  prefetch(gotoLocation: string) {
    console.log('calling prefetch');
    if (this.prefetchedLocations.includes(gotoLocation))
      return;
    let link = document.createElement("link")
    link.setAttribute("rel", "prefetch")
    link.setAttribute("href", gotoLocation)
    document.body.appendChild(link)
    this.prefetchedLocations.push(gotoLocation)
  }
  constructor() {
    this.debouncedPrefetch = debounce(this.prefetch, 10)
  }
  debouncedPrefetch(url: string) {
  }
  onHover() {
    this.iconFlipState = 'end'
  }
  doMouseLeave() {
    this.iconFlipState = 'normal'
  }

  showNew() { 
    try {
      let match = this.card.tagline.match(/\d{4}-\d{1,2}-\d{1,2}/)
      if (match) {
        let lastModified = moment(match[0])
        return moment.duration(moment().diff(lastModified)).weeks() < 2
      }
    }
    catch (e) {
      console.error('Error parsing date: ' + this.card.tagline);
    }

    return false
  }
}


<div class="card" (click)="goto(card.url)" (mouseenter)="debouncedPrefetch(card.url);onHover()" (mouseleave)="doMouseLeave()">

  <div class="new-corner" *ngIf="first && showNew()">New!</div>

  <div class="icon-container">
    <i class="card-img-top" ngClass={{card.icon}} [@iconFlipState]="iconFlipState"></i>
  </div>

  <div class="card-body">
    <h5 class="card-title">{{ card.title }}</h5>
    <p class="card-text">{{ card.description }}</p>
  </div>

  <div class="card-text">
    <div class="btn-group" *ngIf="first">
      <a [href]="card.buttons[0].url" [title]="card.buttons[0].title" class="btn btn-primary">{{ card.buttons[0].label }}</a>
      <a href="/posts/" class="btn btn-primary" title="All Posts">All</a>
    </div>
    <a [href]="card.url" [title]="card.title" class="btn btn-primary" *ngIf="!first">{{ card.buttons[0].label }}</a>
  </div>

  <div class="card-footer" *ngIf="card.tagline"><small>{{card.tagline}}</small></div>
</div>

// src/components/card.vue
<template lang="pug">
.card(@click='goto(url)' @mouseover='debouncedPrefetch(url)')
  .new-corner(v-if="tagline && showNew") New!
  .icon-container
    i.card-img-top(v-bind:class='icon')
  .card-body
    h5.card-title {{ cardTitle }}
    p.card-text {{ excerpt }}
  .card-text
    a.btn.btn-primary(v-bind:href='url' v-bind:title='cardTitle' v-if='buttons.length == 1') {{ buttons[0].label }}
    .btn-group(role='group' aria-label='Blog Posts' v-if='buttons.length > 1')
      a.btn.btn-primary(v-bind:href='buttons[0].url' v-bind:title='buttons[0].title') {{ buttons[0].label }}
      a.btn.btn-primary(href='/posts/' title='All Posts') All
  //- Hidden only on md by the combination of .d-md-none.d-lg-block
  .card-footer(v-if='tagline')
    small {{ tagline }}
</template>

<style lang="scss" scoped>
$primary: #406275;
$dark: #43464A;
$light: #DEE3E6;
$white: #f5f7f8;

small {
  color: $dark;
}
.card {
  box-shadow: 12px 12px 2px 1px rgba(67, 70, 74, .5);
  border-top: 0;
  border-radius: 10px;
  height: 20rem;
  min-width: 5rem;
  overflow: hidden;
  container-type: inline-size;

  .card-text {
    > .btn, > .btn-group {
      position: absolute;
      right: 1rem;
      bottom: 1rem;
    }

    > .btn-group > .btn:nth-child(1) {
      border-right: 2px solid #43464A66;
    }
  }

  .new-corner {
    position: absolute;
    top: 0;
    left: 0;
    padding: .4em 3em;

    transform: rotateZ(-45deg) translateX(-2.2em) translateY(-1.5em);
    background-color: #e7e556d8;
  }

  .card-body {
    padding: 20px 30px 30px;
  }


  @container (max-width: 19em) {
    .card-footer {
      display: none;
    }
  }

  // @container (max-width: 768px) {
  //   .card-footer {
  //     display: block;
  //   }
  // }

  .icon-container {
    border: $primary solid 2px;
    border-radius: 100px;
    margin: 20px auto;
    padding: 30px;
    width: 200px;
  }

  .fas {
    color: $primary;
    background-color: $white;
    font-size: 3em;
    text-align: center;
  }

  &:hover {
    cursor: pointer;
    .fas {
      animation: rotation .5s;
    }
  }
}

@keyframes rotation {
  from {
      transform: rotateY(0deg);
  }

  50% {
      transform: rotateY(180deg);
  }

  to {
      transform: rotateY(360deg);
  }
}
</style>

<script>
import debounce from 'lodash/debounce';
import moment from 'moment'; 

export default {
  props: ['cardTitle', 'excerpt', 'icon', 'buttons', 'url', 'tagline'],
  created() {
    // Debouncing with Lodash
    this.debouncedPrefetch = debounce(this.prefetch, 10)
  },
  unmounted() {
    // Cancel the timer when the component is removed
    this.debouncedPrefetch.cancel()
  },
  data() {
    return {
      prefetchedLocations: []
    }
  },
  computed: {
    showNew() { 
      try {
        let match = this.tagline.match(/\d{4}-\d{1,2}-\d{1,2}/)
        if (match) {
          let lastModified = moment(match[0])
          return moment.duration(moment().diff(lastModified)).weeks() < 2
        }
      }
      catch (e) {
        console.error('Error parsing date: ' + this.tagline);
      }

      return false
    }
  },
  methods: {
    goto: function (gotoLocation) {
      document.location.pathname = gotoLocation
    },
    prefetch: function (gotoLocation) {
      if (this.prefetchedLocations.includes(gotoLocation))
        return;
      let link = document.createElement("link")
      link.setAttribute("rel", "prefetch")
      link.setAttribute("href", gotoLocation)
      document.body.appendChild(link)
      this.prefetchedLocations.push(gotoLocation)
    }
  }
}
</script>
