// src/app/shared/comment-form/comment-form.component.ts
import { Component, Input } from '@angular/core';
import { CommentFormData } from './comment-form-data';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { NetlifyFormsService } from '../../blog/netlify-forms.service';

@Component({
  selector: 'app-comment-form',
  templateUrl: './comment-form.component.pug',
  styleUrls: ['./comment-form.component.scss']
})
export class CommentFormComponent {
  @Input() postId?: string;
  @Input() postTitle?: string;
  beingSubmitted: boolean = false;
  isSuccess = false;
  isError = false;
  expanded = false;
  errorMessage?: string;
  
  commentForm!: FormGroup;
  commentData: CommentFormData = { name: '', comment: '', 'form-name': 'post-comment-form', 'post-id': 'unknown' };

  closeError() {
    this.errorMessage = '';
  }

  get name() { return this.commentForm.get('name'); }
  get comment() { return this.commentForm.get('comment'); }

  constructor(private formBuilder: FormBuilder,
    private router: Router,
    private netlifyForms: NetlifyFormsService) {
    // this.title = this.postTitle || decodeURIComponent((window.location.search.match(/post[tT][iI][tT][lL][eE]=(.+)/) || [undefined, undefined])[1] || '') || ('post #' + this.computedPostId);
  }

  ngOnInit(): void {
    this.commentForm = new FormGroup({
      name: new FormControl(this.commentData.name, Validators.required),
      email: new FormControl(this.commentData.email, Validators.email),
      url: new FormControl(this.commentData.url),
      comment: new FormControl(this.commentData.comment, Validators.required)
    });
  
  }

  submit() {
    try {
      console.log("submit");
      this.beingSubmitted = true;

      this.netlifyForms.submitFeedback(this.commentForm.value as CommentFormData).subscribe({
        next: (v) => {
          this.commentForm.reset();
          this.isSuccess = true;
          this.beingSubmitted = false;
        },
        error: (err) => {
          console.error("There was an error with form submission", err);
          this.isError = true;
          this.errorMessage = err;
        }
    });

      return false;
      // }
    } catch (e) {
      this.isError = true;
      this.beingSubmitted = false;
      console.error(e);
    }
    return false;
  }
}
<div class="container" [ngClass]="containerClass">
  <form class="needs-validation" id="commentForm" name="post-comment-form" data-netlify="true" netlify-honeypot="validate" novalidate="novalidate" #formRef="ngForm">
    <div class="alert alert-danger mt-3" role="alert" *ngIf="isError">
      <h4 class="alert-heading">Oh, no!</h4>
      <div id="expandDetails" *ngIf="!expanded"><span>Something didn't work. </span><a (click)="expanded=true" role="button" style="font-size:.9em">Expand Details +</a></div>
      <div id="errorDetails" *ngIf="expanded">
        <h5>We sent the request but got this response:</h5>
        <p>{{ errorMessage }}</p>
      </div>
      <hr />
      <p class="mb-0">Please try reloading the page.</p>
    </div>
    <div class="alert alert-success mt-3" role="alert" *ngIf="isSuccess">
      <h4 class="alert-heading">Thank you!</h4>
      <p>Your comment was successfully submitted.</p>
    </div>
    <fieldset [disabled]="isSuccess" *ngIf="!isSuccess &amp;&amp; !isError"><input name="postid" type="hidden" id="postid" placeholder="model.postid" /><input type="hidden" name="model.posttitle" />
      <div class="postTitle" *ngIf="postTitle">
        <h2>Comment on &quot;{{ postTitle }}&quot;</h2>
      </div>
      <div class="mb-0 mt-3"><label class="form-label mb-0" for="name">Name: </label></div>
      <div class="mb-3"><input class="form-control" name="name" type="text" id="name" required="required" [(ngModel)]="model.name" #name="ngModel" />
        <div *ngIf="name?.invalid &amp;&amp; (name?.dirty || name?.touched)" style="color:#b87460">What shall I call you?</div>
      </div>
      <div class="mb-0"><label class="form-label mb-0" for="email">Email: </label></div>
      <div class="mb-1"><input class="form-control" name="email" type="email" [(ngModel)]="model.email" #email="ngModel" email="model.email" /></div>
      <div class="mb-3">
        <div class="form-text">Not displayed but the md5 hash is used for Gravatar image.</div>
      </div>
      <div class="mb-0"><label class="form-label mb-0" for="url">URL: </label></div>
      <div class="mb-3"><input class="form-control" name="url" type="text" id="url" [(ngModel)]="model.url" #url="ngModel" /></div>
      <div class="mb-0"><label class="form-label mb-0" for="comment">Comment/s: </label></div>
      <div class="mb-3"><textarea class="form-control" name="comment" id="comment" required="required" [(ngModel)]="model.comment" #comment="ngModel"></textarea>
        <div *ngIf="comment?.invalid &amp;&amp; (comment?.dirty || comment?.touched)" style="color:#b87460">Umm... you wanted to say something, right?</div>
      </div>
      <div class="mb-0" hidden="hidden"><label class="form-label mb-0" for="validate">Validate: </label></div>
      <div class="mb-3" hidden="hidden"><input class="form-control" id="human" type="text" name="validate" placeholder="Are you human?" /></div>
      <div class="mb-1"><button class="btn btn-primary" type="submit" *ngIf="!beingSubmitted" id="submitButton" [disabled]="!name.valid || !comment.valid || (email.touched && email.value != '' && !email.valid)">Submit</button>
        <div class="spinner-border text-primary" role="status" *ngIf="beingSubmitted"><span class="visually-hidden">Submitting...</span></div>
        <div class="alert alert-primary mt-3" role="alert" *ngIf="postId">All submissions are reviewed before being posted.</div>
      </div>
    </fieldset>
  </form>
</div>

// src/components/commentForm.vue
<template lang="pug">
form#commentForm.needs-validation(name='commentForm' data-netlify='true' netlify-honeypot='validate' novalidate @submit='submit()' )
  .alert.alert-danger.mt-3(role="alert" v-if="isError") 
    h4.alert-heading Oh, no!
    #expandDetails(v-show="!expanded")
      span Something didn't work. 
      a(@click="expanded=true" data-bs-toggle="collapse" data-bs-target="#errorDetails" role="button" style="font-size:.9em") Expand Details +
    .collapse#errorDetails
      h5 We sent the request but got this response:
      p {{ errorMessage }}
    hr
    p.mb-0 Please try reloading the page.
  .alert.alert-success.mt-3(role="alert" v-if="isSuccess") 
    h4.alert-heading Thank you!
    p Your comment was successfully submitted.
  fieldset(v-bind:disabled="isSuccess")
    input(type="hidden" name="form-name" value="commentForm")
    label(for='post-id' hidden) Post ID: 
    input(type="hidden" name="post-id" v-bind:value="postId")
    label(for='post-title' hidden) Post Title: 
    input(type="hidden" name="post-title" v-bind:value="computedPostTitle")
    .postTitle(v-if="computedPostId")
      h2 Comment on &quot;{{ computedPostTitle }}&quot;
    .mb-0.mt-3
      label.form-label.mb-0(for='name') Name: 
    .mb-3
      input.form-control(type='text' name='name' id='name' placeholder='Your name' required)
      .invalid-feedback What shall I call you?
    .mb-0
      label.form-label.mb-0(for='email') Email: 
    .mb-1
      input.form-control(type='email' name='email' id='email' placeholder='your-name@example.com')
    .mb-3
      .form-text Not displayed but the md5 hash is used for Gravatar image.
    .mb-0
      label.form-label.mb-0(for='url') URL: 
    .mb-3
      input.form-control(type='url' name='url' id='url' placeholder='www.my-awesome-site.com')
    .mb-0
      label.form-label.mb-0(for='comment') Comment/s: 
    .mb-3
      textarea.form-control(name='comment' id='comment' required)
      .invalid-feedback Umm... you wanted to say something, right?
    .mb-0(hidden)
      label.form-label.mb-0(for='validate') Validate: 
    .mb-3(hidden)
      input#url.form-control(type='text' name='validate' placeholder='Are you human?')
    .mb-1
      button.btn.btn-primary(type='submit' v-if="!beingSubmitted" id='submitButton') Submit
      .spinner-border.text-primary(role="status" v-if="beingSubmitted")
        span.visually-hidden Submitting...
      .alert.alert-primary.mt-3(role="alert" v-if="postId") All submissions are reviewed before being posted.
</template>

<style lang="scss" scoped>
h1 {
  z-index: 9;
}
</style>

<script>
export default {
  props: ['postId', 'postTitle'],
  data: function () {
    return {
      beingSubmitted: false,
      isSuccess: false,
      isError: false,
      expanded: false,
    }
  },
  computed: {
    computedPostId() {
      try {
        return this.postId || (window.location.search.match(/postI[dD]=(\d+)/) || [,false])[1];
      }
      catch(e) {
        console.error('Error reading post ID: ' + e);
        return 'unknown'
      }
    },
    computedPostTitle() {
      try {
        return this.postTitle || decodeURIComponent((window.location.search.match(/post[tT][iI][tT][lL][eE]=(.+)/) || [undefined, undefined])[1] || '') || ('post #' + this.computedPostId);
      }
      catch(e) {
        console.error('Error reading post title: ' + e);
      }
    }
  },
  methods: {
    submit: function () {
      try {
        this.beingSubmitted = true;
        event.preventDefault()
        event.stopPropagation()
        let form = this.$el;
        if (form.checkValidity()) {
          let formData = new FormData(form);
          fetch("/", {
            method: "POST",
            headers: { "Content-Type": "application/x-www-form-urlencoded" },
            body: new URLSearchParams(formData).toString(),
          })
          .then((response) => {
            this.beingSubmitted = false
            if (response.ok) {
              this.isSuccess = true
            }
            else {
              console.error(response);
              this.isError = true
              form.classList.remove("was-validated");
              this.errorMessage = response.status + " - " + response.statusText
            }
          })
        } else {
          this.beingSubmitted = false;
          form.classList.add("was-validated");
          return false;
        }
      } catch (e) {
        this.isError = true;
        this.beingSubmitted = false;
        console.error(e);
      }
    },
  },
};
</script>
