// src/app/minicard/minicard.component.ts
import { Component, Input, OnInit } from '@angular/core';
import debounce from 'lodash/debounce';

@Component({
  selector: 'app-minicard',
  templateUrl: './minicard.component.html', 
  styleUrls: ['./minicard.component.scss']
})
export class MinicardComponent {

  prefetchedLocations: string[] = [];
  @Input() card: any;
  @Input() first: boolean = false;
  prefetch(gotoLocation: string) {
    console.log('calling prefetch');
    if (this.prefetchedLocations.includes(gotoLocation))
      return;
    let link = document.createElement("link")
    link.setAttribute("rel", "prefetch")
    link.setAttribute("href", gotoLocation)
    document.body.appendChild(link)
    this.prefetchedLocations.push(gotoLocation)
  }
  constructor() {
    this.debouncedPrefetch = debounce(this.prefetch, 10)
  }
  debouncedPrefetch(url: string) {
  }
  goto(gotoLocation: string) {
    document.location = gotoLocation
  }
}

<div class="card" (click)="goto(card.link)">
  <div class="card-body">
      <div class="link">
        <a [href]="card.link" [title]="card.isExternal ? 'Be careful out there' : ''">
          <i class="fas fa-angle-double-right" *ngIf="!card.isExternal"></i>
          <i class="fas fa-external-link-alt" *ngIf="card.isExternal"></i>
        </a>
      </div>
    <h4 class="cardTitle"><i class="card-img-top" ngClass={{card.icon}}></i>{{ card.title }}</h4>
    <p class="card-text">{{ card.description }}</p>
  </div>
</div>

// src/components/minicard.vue
<template lang="pug">
.card(@click='goto(link)' @mouseover='debouncedPrefetch(link)')
  .card-body
    .link
      a(v-bind:href='link' v-bind:title='cardTitle') 
        i(v-if="!isExternal" class='fas fa-angle-double-right')
        i(v-if="isExternal" class='fas fa-external-link-alt')
    h4.card-title 
      i.card-img-top(v-bind:class='icon')
      | {{ cardTitle }}
    p.card-text {{ description }}
</template>

<style lang="scss" scoped>
$primary: #406275;
$dark: #43464A;
$light: #DEE3E6;
$white: #f5f7f8;
.card {
  .card-body {
    .link {
      float:right;
    }
  }
  &:hover {
    cursor: pointer;
    border-color: $primary;
  }
  .fas, .fab {
    width: 1.5em;
  }

  a i.fas, a i.fab {
    font-size: 2em;
  }
}
</style>

<script>
import debounce from 'lodash/debounce';

export default {
  created() {
    // Debouncing with Lodash
    this.debouncedPrefetch = debounce(this.prefetch, 10)
  },
  unmounted() {
    // Cancel the timer when the component is removed
    this.debouncedPrefetch.cancel()
  },
  props: ['cardTitle', 'description', 'icon', 'buttonText', 'link', 'isExternal'],
  data() {
    return {
      prefetchedLocations: []
    }
  },
  methods: {
    goto: function (gotoLocation) {
      document.location = gotoLocation
    },
    prefetch: function (gotoLocation) {
      if (this.prefetchedLocations.includes(gotoLocation))
        return;
      let link = document.createElement("link")
      link.setAttribute("rel", "prefetch")
      link.setAttribute("href", gotoLocation)
      document.body.appendChild(link)
      this.prefetchedLocations.push(gotoLocation)
    }
  }
}
</script>
